//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/UI/Input/UIInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UIInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UIInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UIInputAction"",
    ""maps"": [
        {
            ""name"": ""MainUI"",
            ""id"": ""c1ee5e4b-f8b2-44cf-8fb2-9c0cca869a6e"",
            ""actions"": [
                {
                    ""name"": ""Setting"",
                    ""type"": ""Button"",
                    ""id"": ""2a7e9eb0-ad97-49d6-9283-f3137d037000"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChoiceItem"",
                    ""type"": ""Button"",
                    ""id"": ""899ef13a-9f99-46ce-8d69-045785c06d9c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rune"",
                    ""type"": ""Button"",
                    ""id"": ""ab4d5048-c5ab-413a-b38e-56528d955b6d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6bab6afd-374b-4da5-9f10-ad83f041a92d"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Setting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c5e7464-9434-4c0f-8781-7d355d27c12e"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChoiceItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c6f79e4-8267-4fa8-8a6a-9e95388a297a"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rune"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ChoiceMapUI"",
            ""id"": ""b83cdac1-0164-4627-843f-d33bef3982b8"",
            ""actions"": [
                {
                    ""name"": ""OpenWorldMap"",
                    ""type"": ""Button"",
                    ""id"": ""74d3af17-21ca-4f9c-89e3-8adb98986253"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse"",
                    ""type"": ""Button"",
                    ""id"": ""b4d89581-1563-48d5-93cc-b8018d075588"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""23ca1801-6ae6-46f5-8544-a4501efd1782"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenWorldMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82a67aa8-19f8-4b75-8b75-0c933be69c69"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MainUI
        m_MainUI = asset.FindActionMap("MainUI", throwIfNotFound: true);
        m_MainUI_Setting = m_MainUI.FindAction("Setting", throwIfNotFound: true);
        m_MainUI_ChoiceItem = m_MainUI.FindAction("ChoiceItem", throwIfNotFound: true);
        m_MainUI_Rune = m_MainUI.FindAction("Rune", throwIfNotFound: true);
        // ChoiceMapUI
        m_ChoiceMapUI = asset.FindActionMap("ChoiceMapUI", throwIfNotFound: true);
        m_ChoiceMapUI_OpenWorldMap = m_ChoiceMapUI.FindAction("OpenWorldMap", throwIfNotFound: true);
        m_ChoiceMapUI_Mouse = m_ChoiceMapUI.FindAction("Mouse", throwIfNotFound: true);
    }

    ~@UIInputAction()
    {
        UnityEngine.Debug.Assert(!m_MainUI.enabled, "This will cause a leak and performance issues, UIInputAction.MainUI.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_ChoiceMapUI.enabled, "This will cause a leak and performance issues, UIInputAction.ChoiceMapUI.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MainUI
    private readonly InputActionMap m_MainUI;
    private List<IMainUIActions> m_MainUIActionsCallbackInterfaces = new List<IMainUIActions>();
    private readonly InputAction m_MainUI_Setting;
    private readonly InputAction m_MainUI_ChoiceItem;
    private readonly InputAction m_MainUI_Rune;
    public struct MainUIActions
    {
        private @UIInputAction m_Wrapper;
        public MainUIActions(@UIInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Setting => m_Wrapper.m_MainUI_Setting;
        public InputAction @ChoiceItem => m_Wrapper.m_MainUI_ChoiceItem;
        public InputAction @Rune => m_Wrapper.m_MainUI_Rune;
        public InputActionMap Get() { return m_Wrapper.m_MainUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainUIActions set) { return set.Get(); }
        public void AddCallbacks(IMainUIActions instance)
        {
            if (instance == null || m_Wrapper.m_MainUIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainUIActionsCallbackInterfaces.Add(instance);
            @Setting.started += instance.OnSetting;
            @Setting.performed += instance.OnSetting;
            @Setting.canceled += instance.OnSetting;
            @ChoiceItem.started += instance.OnChoiceItem;
            @ChoiceItem.performed += instance.OnChoiceItem;
            @ChoiceItem.canceled += instance.OnChoiceItem;
            @Rune.started += instance.OnRune;
            @Rune.performed += instance.OnRune;
            @Rune.canceled += instance.OnRune;
        }

        private void UnregisterCallbacks(IMainUIActions instance)
        {
            @Setting.started -= instance.OnSetting;
            @Setting.performed -= instance.OnSetting;
            @Setting.canceled -= instance.OnSetting;
            @ChoiceItem.started -= instance.OnChoiceItem;
            @ChoiceItem.performed -= instance.OnChoiceItem;
            @ChoiceItem.canceled -= instance.OnChoiceItem;
            @Rune.started -= instance.OnRune;
            @Rune.performed -= instance.OnRune;
            @Rune.canceled -= instance.OnRune;
        }

        public void RemoveCallbacks(IMainUIActions instance)
        {
            if (m_Wrapper.m_MainUIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainUIActions instance)
        {
            foreach (var item in m_Wrapper.m_MainUIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainUIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainUIActions @MainUI => new MainUIActions(this);

    // ChoiceMapUI
    private readonly InputActionMap m_ChoiceMapUI;
    private List<IChoiceMapUIActions> m_ChoiceMapUIActionsCallbackInterfaces = new List<IChoiceMapUIActions>();
    private readonly InputAction m_ChoiceMapUI_OpenWorldMap;
    private readonly InputAction m_ChoiceMapUI_Mouse;
    public struct ChoiceMapUIActions
    {
        private @UIInputAction m_Wrapper;
        public ChoiceMapUIActions(@UIInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenWorldMap => m_Wrapper.m_ChoiceMapUI_OpenWorldMap;
        public InputAction @Mouse => m_Wrapper.m_ChoiceMapUI_Mouse;
        public InputActionMap Get() { return m_Wrapper.m_ChoiceMapUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ChoiceMapUIActions set) { return set.Get(); }
        public void AddCallbacks(IChoiceMapUIActions instance)
        {
            if (instance == null || m_Wrapper.m_ChoiceMapUIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ChoiceMapUIActionsCallbackInterfaces.Add(instance);
            @OpenWorldMap.started += instance.OnOpenWorldMap;
            @OpenWorldMap.performed += instance.OnOpenWorldMap;
            @OpenWorldMap.canceled += instance.OnOpenWorldMap;
            @Mouse.started += instance.OnMouse;
            @Mouse.performed += instance.OnMouse;
            @Mouse.canceled += instance.OnMouse;
        }

        private void UnregisterCallbacks(IChoiceMapUIActions instance)
        {
            @OpenWorldMap.started -= instance.OnOpenWorldMap;
            @OpenWorldMap.performed -= instance.OnOpenWorldMap;
            @OpenWorldMap.canceled -= instance.OnOpenWorldMap;
            @Mouse.started -= instance.OnMouse;
            @Mouse.performed -= instance.OnMouse;
            @Mouse.canceled -= instance.OnMouse;
        }

        public void RemoveCallbacks(IChoiceMapUIActions instance)
        {
            if (m_Wrapper.m_ChoiceMapUIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IChoiceMapUIActions instance)
        {
            foreach (var item in m_Wrapper.m_ChoiceMapUIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ChoiceMapUIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ChoiceMapUIActions @ChoiceMapUI => new ChoiceMapUIActions(this);
    public interface IMainUIActions
    {
        void OnSetting(InputAction.CallbackContext context);
        void OnChoiceItem(InputAction.CallbackContext context);
        void OnRune(InputAction.CallbackContext context);
    }
    public interface IChoiceMapUIActions
    {
        void OnOpenWorldMap(InputAction.CallbackContext context);
        void OnMouse(InputAction.CallbackContext context);
    }
}
